version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env 

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
